name: animal-shelter
services:
  animal-shelter-db:
    image: postgres:15
    container_name: animal-shelter-db
    environment:
      POSTGRES_DB: shelter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - animal-shelter-net

  animal-shelter-app:
    build:
      context: .
      dockerfile: animal-shelter/animal-shelter.Dockerfile
    container_name: animal-shelter-app
    ports:
      - "8080:8080"
    networks:
      - animal-shelter-net
    depends_on:
      - animal-shelter-db

  admin-server:
    build:
      context: .
      dockerfile: admin-server/admin-server-app.Dockerfile
    container_name: admin-server
    environment:
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server:8085
    ports:
      - "8085:8085"
    networks:
      - animal-shelter-net
    depends_on:
      - animal-shelter-app

networks:
  animal-shelter-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
