server:
  port: 8085

spring:
  application:
    name: SpringAdmin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true
    endpoint:
      metrics:
        enabled: true