server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://admin-server:8085
        username: admin
        password: javaguru
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
    create-schemas: true
    baseline-on-migrate: true
    default-schema: webapp
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://animal-shelter-db:5432/shelter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        default_schema: webapp

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-mail
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 3000
          writetimeout: 3000
          connectiontimeout: 3000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

minio:
  url: http://minio:9000
  accessKey: admin
  secretKey: password
  bucket-name: image-bucket
  secure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true
    endpoint:
      metrics:
        enabled: true